### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by eightsixeight** [nanopool/nanominer#249]
here are logs.

C:\nanominer\nanominer-windows-3.3.5>nanominer.exe config_ergo.ini
Exception 0xc0000005 0x0 0x7ffdcd632fff 0x1d815b50000
PC=0x1d815b50000
signal arrived during external code execution

syscall.Syscall6(0x7ffdcd3856b0, 0x6, 0x2, 0x1, 0x6, 0x0, 0x0, 0x81, 0x0, 0x0, ...)
        C:/Go/src/runtime/syscall_windows.go:185 +0xfc
internal/syscall/windows.WSASocket(0x100000002, 0xc000000006, 0x0, 0x8100000000, 0xc000089360, 0x10, 0x10)
        C:/Go/src/internal/syscall/windows/zsyscall_windows.go:117 +0xa5
net.sysSocket(0x2, 0x1, 0x6, 0x70b59db3, 0x0, 0xc0000a3470)
        C:/Go/src/net/sock_windows.go:20 +0x66
net.(*ipStackCapabilities).probe(0x7100eec0)
        C:/Go/src/net/ipsock_posix.go:27 +0x55
net.(*ipStackCapabilities).probe-fm()
        C:/Go/src/net/ipsock.go:31 +0x31
sync.(*Once).Do(0x7100eec0, 0xc0000abab0)
        C:/Go/src/sync/once.go:44 +0xba
net.supportsIPv4map(0xc0000a34a0)
        C:/Go/src/net/ipsock.go:46 +0x5e
net.favoriteAddrFamily(0x70db1848, 0x3, 0x70e0fd20, 0xc0000a34a0, 0x0, 0x0, 0x70db2015, 0x6, 0x3f31930b461d97e1, 0xa1f42114da25d3ea)
        C:/Go/src/net/ipsock_posix.go:120 +0x8f
net.internetSocket(0x70e0f0a0, 0xc0000880a0, 0x70db1848, 0x3, 0x70e0fd20, 0xc0000a34a0, 0x0, 0x0, 0x1, 0x0, ...)
        C:/Go/src/net/ipsock_posix.go:140 +0xc8
net.(*sysListener).listenTCP(0xc0000abcc0, 0x70e0f0a0, 0xc0000880a0, 0xc0000a34a0, 0x70e0dd60, 0xc0000a34a0, 0x3)
        C:/Go/src/net/tcpsock_posix.go:159 +0xbe
net.(*ListenConfig).Listen(0xc0000abd50, 0x70e0f0a0, 0xc0000880a0, 0x70db1848, 0x3, 0xc000089350, 0xc, 0xc0000abd70, 0x2, 0x2, ...)
        C:/Go/src/net/dial.go:604 +0x575
net.Listen(0x70db1848, 0x3, 0xc000089350, 0xc, 0x4, 0xc000089350, 0xc, 0x70c2e39b)
        C:/Go/src/net/dial.go:674 +0x85
main/app/servers/tcp/ethman.Start(0x70e0f060, 0xc000084280, 0xfffffffffffff2fb)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/servers/tcp/ethman/ethman.go:56 +0xd1
main.StartMainLoop()
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/service.go:347 +0x24e
main._cgoexpwrap_09b6841e9a8e_StartMainLoop()
        _cgo_gotypes.go:591 +0x27

goroutine 21 [select]:
main/grace.ShutdownContext.func1(0x70e0f060, 0xc000084280, 0xc00006d000)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/grace/shutdown.go:14 +0xbd
created by main/grace.ShutdownContext
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/grace/shutdown.go:13 +0x68

goroutine 20 [sleep]:
time.Sleep(0x3b9aca00)
        C:/Go/src/runtime/time.go:105 +0x164
github.com/valyala/fasthttp.init.0.func1()
        C:/Users/user/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/header.go:1443 +0x31
created by github.com/valyala/fasthttp.init.0
        C:/Users/user/go/pkg/mod/github.com/valyala/fasthttp@v1.6.0/header.go:1441 +0x41

goroutine 22 [select]:
main/app/client.(*MinerClient).SendMessage(0xc000230000, 0x70e0f060, 0xc000084280, 0xc00000e280, 0x17, 0x20, 0x70db2d1e, 0x9)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/client/sender.go:113 +0x146
main/app/client.(*MinerClient).CommandSender(0xc000230000, 0x70e0f060, 0xc000084280, 0x70db2d1e, 0x9)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/client/sender.go:76 +0x5cb
main/app/client.Start(0x70e0f060, 0xc000084280, 0xc00022a000, 0xc000002480)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/client/client.go:111 +0x3e0
main/app/servers/tcp/miner.Start.func1(0xc0000be320, 0x70e0f060, 0xc000084280)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/servers/tcp/miner/miner.go:16 +0x93
created by main/app/servers/tcp/miner.Start
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/servers/tcp/miner/miner.go:11 +0x5a

goroutine 5 [chan receive]:
main/app/client.(*MinerClient).Read(0xc000230000, 0x70e0f060, 0xc000084280)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/client/client.go:66 +0x4d
created by main/app/client.Start
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/client/client.go:100 +0x1d4

goroutine 6 [chan send]:
main/app/client.(*MinerClient).Write(0xc000230000, 0x70e0f060, 0xc000084280)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/client/client.go:80 +0x7e
created by main/app/client.Start
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/client/client.go:101 +0x212

goroutine 7 [select]:
main/app/client.(*MinerClient).MessageReader(0xc000230000, 0x70e0f060, 0xc000084280)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/client/reader.go:36 +0x1ca
created by main/app/client.Start
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/client/client.go:103 +0x250

goroutine 8 [select]:
main/app/client.(*MinerClient).MessageSender(0xc000230000, 0x70e0f060, 0xc000084280)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/client/sender.go:28 +0x172
created by main/app/client.Start
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/app/client/client.go:104 +0x28e
rax     0x7ffdca3b0b92
rbx     0x7ffdca3b0b90
rcx     0x77
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x0
rsp     0x6b5f5fe8e0
r8      0x97d
r9      0x97d
r10     0x97d
r11     0x97d
r12     0xc000007a
r13     0x0
r14     0x7ffdca3b0b92
r15     0x7ffdcd430000
rip     0x1d815b50000
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b

**Comment by rtyz** [comment]
Does setting `mport = 0` in config help?

**Comment by David345895** [comment]
Same problem I am facing. Miner is Crashing after starting for coins RVN, ETC, ETH & XMR. My miner version is 3.5.5 !
