### ISSUE TITLE
updated to 3.3.5-cuda11 today, now panic on start

### ISSUE THREAD

**Issue by sircambridge** [nanopool/nanominer#256]
GPU0 t=41°C fan 40% power 125.03W. Total power: 125.03W
panic: runtime error: slice bounds out of range

goroutine 185 [running, locked to thread]:
main/updater.getFilePathWithoutFirstFolder(0xc0002f4000, 0x1e, 0xc0002f4001, 0x1e)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/updater/updater.go:95 +0x150
main/updater.getSuitableFileName(0xc0002f4000, 0x1f, 0x3784c46, 0xc00005a080)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/updater/updater.go:69 +0x7a
main/updater.replaceFiles(0xc004550000, 0x3784c46, 0x0, 0x0)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/updater/update_windows.go:31 +0x1a5
main/updater.ProcessUpdate(0x0)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/updater/updater.go:51 +0xcf
main.ProcessUpdate(0x70dcaca8)
        C:/Gitlab-Runner/builds2/14a557a7/0/cryptogen/dev/cryptogen-miner/service/service.go:155 +0x29
main._cgoexpwrap_09b6841e9a8e_ProcessUpdate(0x0)
        _cgo_gotypes.go:371 +0x29

**Comment by Death916** [comment]
having same issue

**Comment by Death916** [comment]
having same issue
